app_cms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index_view, name='index'),
    path('', views.article_list, name='article_list'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
    path('new/article/', views.new_article, name='new_article'),
    
    path('edit/<int:pk>/', views.edit_article, name='edit_article'),
    path('delete/<int:pk>/', views.delete_article, name='delete_article'),
    
    path('profile/', views.profile_view, name='profile'),
    path('update_profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('upload_profile_picture/', views.upload_profile_picture, name='upload_profile_picture'),
    
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

app_polls/urls.py
from django.urls import path

from . import views

app_name = "app_polls"
urlpatterns = [
    path("", views.polls, name="polls"),
    path('new/poll/', views.new_poll, name='new_poll'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mypoll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')), # matches the root URL
    path('polls/', include('polls.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_cms.urls")),
    path('polls/', include("app_polls.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

app_cms/models.py
from django.db import models

# Create your models here.
    
class SimpleUser(models.Model):
    profile_pic = models.ImageField(null=True, blank=True) # upload_to='profile_imgs/'
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    phn_num = models.IntegerField(null=True, blank=True)
    password = models.CharField(max_length=200)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.username} - {self.email}"
    
    @property
    def profilePic(self):
        try:
            url = self.profile_pic.url
        except:
            url = ''
        return url
    
    
class Article(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(null=True, blank=True) # upload_to='article_imgs/'
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    def increment_view_count(self):
        self.view_count += 1
        self.save()
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

app_cms/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.hashers import make_password, check_password
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views import View
import json
from django.core.files.storage import FileSystemStorage
from .utils import get_user_profile
from django.contrib import messages
from django.utils.crypto import get_random_string
from datetime import datetime
from pathlib import Path


# def index_view(request):
#     return render ( request , 'base.html' )

@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if not username or not password:
            messages.error(request, 'Username and password are required.')
            return redirect('login')

        try:
            user = SimpleUser.objects.get(username=username)
            if check_password(password, user.password):  # Check hashed password
                request.session['user_id'] = user.id  # Set user id in session
                messages.success(request, 'Successfully logged in!')
                return redirect('article_list')
            else:
                messages.error(request, 'Invalid username or password.')
        except SimpleUser.DoesNotExist:
            messages.error(request, 'Invalid username or password.')
            
    return render(request, 'app_cms/login.html')



@csrf_exempt
def register_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        phn_num = request.POST['phn_num']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        
        if password == confirm_password:
            # IMPORTANT: Always hash the password before storing!
            hashed_password = make_password(password)
            
            user = SimpleUser(username=username, email=email, phn_num=phn_num, password=hashed_password)
            user.save()
            return redirect('login')
        else:
            pass
    return render(request, 'app_cms/register.html')


def logout_view(request):
    if 'user_id' in request.session:
        del request.session['user_id']
    return redirect('login')


@csrf_exempt
def profile_view(request):
    user_id = request.session.get('user_id')
    is_authenticated = bool(user_id)
    profile = get_user_profile(user_id)
    
    if profile:
        context = {
            'is_authenticated': is_authenticated,
            'profile': profile, 'user_id': user_id
        }
        return render(request, 'app_cms/profile.html', context)
    else:
        return redirect('login')
    
    
@method_decorator(csrf_exempt, name='dispatch')
class UpdateProfileView(View):
    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
            user_id = request.session.get('user_id')

            if not user_id:
                return JsonResponse({'status': 'error', 'message': 'Not authenticated'}, status=401)

            user = SimpleUser.objects.get(pk=user_id)

            # Update the fields
            user.username = data.get('username', user.username)
            # user.email = data.get('email', user.email)
            # user.phn_num = data.get('phn_num', user.phn_num)
            
            # ... update any other fields you want ...

            user.save()
            return JsonResponse({'status': 'success', 'message': 'Profile updated successfully'})
        
        except SimpleUser.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'User not found'}, status=404)
        
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f"Error: {str(e)}"}, status=500)
        
        
def upload_profile_picture(request):
    if request.method == 'POST' and request.FILES['profile_pic']:
        profile_pic = request.FILES['profile_pic']
        user_id = request.session.get('user_id')
        print(user_id)
        
        # Fetch the user instance using the user_id
        user = SimpleUser.objects.get(pk=user_id)

        # Generate a unique filename based on the current timestamp and a random string
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        random_string = get_random_string(length=6)
        new_filename = f"profile_{user_id}_{timestamp}_{random_string}{Path(profile_pic.name).suffix}"

        # Save the uploaded image with the new filename
        fs = FileSystemStorage(location='static/images')
        filename = fs.save(new_filename, profile_pic)
        uploaded_file_url = fs.url(filename)

        # Update the user's profile picture
        user.profile_pic = uploaded_file_url
        user.save()

        return redirect('profile') 

    # return to profile page with some error message if needed
    return redirect('profile')


def new_article(request):
    user_id = request.session.get('user_id')
    is_authenticated = bool(user_id)
    profile = SimpleUser.objects.get(id=user_id)
    context = {
        'is_authenticated': is_authenticated,
        'profile': profile, 'user_id': user_id
        }
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        image = request.FILES['image']
        author = request.POST['author']
        if author == '':
            author = profile.username
        
        # Generate a unique filename based on the current timestamp and a random string
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        random_string = get_random_string(length=6)
        new_filename = f"{author}_{timestamp}_{random_string}{Path(image.name).suffix}"

        # Save the uploaded image with the new filename
        fs = FileSystemStorage(location='static/images/')
        filename = fs.save(new_filename, image)
        uploaded_file_url = fs.url(filename)

        # Save the article
        article = Article(title=title, content=content, image=uploaded_file_url, author=author)
        article.save()
        return redirect('article_list')

    return render(request, 'app_cms/new_article.html', context)


@csrf_exempt
def article_list(request):
    articles = Article.objects.all().order_by('-published_date') # '-' indicates descending order
    user_id = request.session.get('user_id')
    is_authenticated = bool(user_id)
    print(is_authenticated)
    
    # Increment view count only if the user is authenticated
    if user_id and Article.objects.filter(id=user_id).exists():
        article = Article.objects.get(id=user_id)
        article.view_count += 1
        article.save()
    
    try:
        profile = SimpleUser.objects.get(id=user_id)
    except SimpleUser.DoesNotExist:
        profile = None
        # return render(request, 'app_cms/article_list.html')
    context = {
        'is_authenticated': is_authenticated,
        'articles': articles, 'profile': profile, 'user_id': user_id
        }
    return render(request, 'app_cms/article_list.html', context)


def edit_article(request, pk):
    article = Article.objects.get(pk=pk)
    user_id = request.session.get('user_id')
    is_authenticated = bool(user_id)
    
    try:
        profile = SimpleUser.objects.get(id=user_id)
    except (KeyError, SimpleUser.DoesNotExist):
        return redirect('login')  # or wherever you want to redirect them to.
    
    if request.method == 'POST':
        # Get the new details from POST data
        title = request.POST['title']
        content = request.POST['content']
        author = profile.username
        print(author)
        
        
        # If an image is uploaded, handle it
        if 'image' in request.FILES:
            image = request.FILES['image']
            
            # Generate a unique filename based on the current timestamp and a random string
            timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
            random_string = get_random_string(length=6)
            new_filename = f"{author}_{timestamp}_{random_string}{Path(image.name).suffix}"
            
            fs = FileSystemStorage(location='static/images/')
            filename = fs.save(new_filename, image)
            uploaded_file_url = fs.url(filename)
            article.image = uploaded_file_url

        # Update article details
        article.title = title
        article.content = content
        # Update other fields as required

        # Save the changes
        article.save()

        # Redirect to the list or detail view after saving changes
        return redirect('article_detail', pk=article.pk)
    context = {
        'is_authenticated': is_authenticated,
        'article': article, 'profile': profile, 'user_id': user_id
        }

    return render(request, 'app_cms/edit_article.html', context)


def delete_article(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('article_list')


@csrf_exempt
def article_detail(request, pk):
    article = Article.objects.get(pk=pk)
    article.increment_view_count()
    user_id = request.session.get('user_id')
    is_authenticated = bool(user_id)
    
    if user_id:
        profile = SimpleUser.objects.get(id=user_id)
    else:
        profile = None

    context = {
        'is_authenticated': is_authenticated,
        'article': article, 'profile': profile, 'user_id': user_id
        }
    return render(request, 'app_cms/article_detail.html', context)

app_cms/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" href="https://shuvendusingha.onrender.com/favicon.ico" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %} Ahgnis {% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.tiny.cloud/1/8kahlt9ejvfhlb9hsgeb59fz0w52qa796hhhl9ux4ommz5nq/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/tailwind.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@3.3.3/tailwind.min.css" rel="stylesheet">
    </head>

    <body data-user-id="{{ user_id }}" class='flex flex-col bg-gray-600 text-white items-center blur-3xl transition-filter duration-500'>
        {% include "app_cms/navbar.html" %}
        {% include "app_cms/modal.html" %}

        <div id="main_content" class="flex flex-col justify-center mt-[5%] w-[80%]">
            
            {% if request.resolver_match.url_name == 'article_list' %}
                <a href="{% url 'app_polls:polls' %}" class="flex fixed top-0 right-[15%] h-14 w-[10%] items-center justify-center bg-gray-900 hover:bg-emerald-500 transition duration-300 z-10">Create a Poll?</a>
            {% elif request.resolver_match.url_name == 'polls' %}
                <a href="{% url 'article_list' %}" class="flex fixed top-0 right-[15%] h-14 w-auto p-1 items-center justify-center bg-gray-900 hover:bg-emerald-500 transition duration-300 z-10">Go to Article section!</a>
            {% endif %}
            
            {% block content %}

            {% endblock %}
        </div>

        {% include "app_cms/band_footer.html" %}
        
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                console.log("JavaScript is running");
                
                let userId = document.body.getAttribute('data-user-id');
                if (userId) {
                    localStorage.setItem('userId', userId);
                }
            });
            
            window.onload = function() {
                document.body.style.filter = 'none';
            };

            // JavaScript to handle AJAX page changes
            document.addEventListener('DOMContentLoaded', () => {
                const container = document.getElementById('main_content');
            
                document.body.addEventListener('click', event => {
                    if (event.target.matches('[data-link]')) {
                        event.preventDefault();
                        
                        // Fetch the content
                        fetch(event.target.href)
                            .then(response => response.text())
                            .then(data => {
                                container.innerHTML = data;
                                history.pushState(null, null, event.target.href);
                            })
                            .catch(error => console.error('Error:', error));
                    }
                });
            });
            

            tinymce.init({
              selector: 'textarea',
              plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
              toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
              tinycomments_mode: 'embedded',
              tinycomments_author: 'Author name',
              mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
              ],
              ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant"))
            });
          </script>
    </body>
</html>